/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings"];
        trace?: never;
    };
    "/api/settings/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vacancies */
        get: operations["list_vacancies"];
        put?: never;
        /** Add Vacancy */
        post: operations["add_vacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description New hh vacancies waiting for «Откликнуться» / «Пропустить».
         */
        get: operations["review_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Vacancy Status */
        patch: operations["change_vacancy_status"];
        trace?: never;
    };
    "/api/vacancies/queue-new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue All New */
        post: operations["queue_all_new"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Vacancies */
        post: operations["delete_vacancies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/to-companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * To Companies
         * @description E-mails from vacancies on other sites go to «Письма компаниям».
         */
        post: operations["to_companies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vacancy Detail */
        get: operations["vacancy_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/{vid}/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Pipeline */
        patch: operations["update_pipeline"];
        trace?: never;
    };
    "/api/vacancies/{vid}/followup-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Followup Draft */
        get: operations["followup_draft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/{vid}/followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Followup */
        post: operations["send_followup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vacancies/{vid}/followup/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Followup */
        post: operations["close_followup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pipeline */
        get: operations["get_pipeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reminders */
        get: operations["get_reminders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies"];
        put?: never;
        /** Add Company */
        post: operations["add_company"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Companies */
        post: operations["import_companies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Company Status */
        patch: operations["change_company_status"];
        trace?: never;
    };
    "/api/companies/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Companies */
        post: operations["delete_companies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Company */
        patch: operations["update_company"];
        trace?: never;
    };
    "/api/companies/{cid}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mail Preview */
        get: operations["mail_preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mail Test */
        post: operations["mail_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chats */
        get: operations["list_chats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chats History */
        get: operations["chats_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{cid}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply Chat */
        post: operations["reply_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{cid}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hide Chat */
        post: operations["hide_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Answers */
        get: operations["list_answers"];
        /** Save Answers */
        put: operations["save_answers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Answer */
        delete: operations["delete_answer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match Answer
         * @description Which answer the bot would give to this question.
         */
        get: operations["match_answer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{qid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Question */
        delete: operations["delete_question"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Task */
        post: operations["stop_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Task */
        post: operations["start_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global Search */
        get: operations["global_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/{what}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Added */
        Added: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Added */
            added: number;
        };
        /** Answer */
        "Answer-Input": {
            /** Id */
            id?: number | null;
            /**
             * Topic
             * @default
             */
            topic?: string;
            /**
             * Keywords
             * @default
             */
            keywords?: string;
            /**
             * Answer
             * @default
             */
            answer?: string;
        };
        /** Answer */
        "Answer-Output": {
            /** Id */
            id: number | null;
            /**
             * Topic
             * @default
             */
            topic: string;
            /**
             * Keywords
             * @default
             */
            keywords: string;
            /**
             * Answer
             * @default
             */
            answer: string;
        };
        /** AnswerMatch */
        AnswerMatch: {
            /** Topic */
            topic: string | null;
            /** Answer */
            answer: string;
        };
        /** AnswersSave */
        AnswersSave: {
            /** Items */
            items: components["schemas"]["Answer-Input"][];
        };
        /**
         * AutopilotMode
         * @enum {string}
         */
        AutopilotMode: "review" | "auto";
        /** Body_import_companies */
        Body_import_companies: {
            /** File */
            file: string;
        };
        /** Body_upload_resume */
        Body_upload_resume: {
            /** File */
            file: string;
        };
        /** ChatItem */
        ChatItem: {
            /** Id */
            id: number;
            /** Chat Id */
            chat_id: string | null;
            /** Msg Id */
            msg_id: string | null;
            /** Company */
            company: string | null;
            /** Vacancy */
            vacancy: string | null;
            /** Message */
            message: string | null;
            /** Reply */
            reply: string | null;
            /** Robot */
            robot: number | null;
            status: components["schemas"]["ChatStatus"];
            /** Created At */
            created_at: string | null;
            /** Sent At */
            sent_at: string | null;
        };
        /** ChatReply */
        ChatReply: {
            /** Reply */
            reply: string;
        };
        /**
         * ChatStatus
         * @enum {string}
         */
        ChatStatus: "pending" | "info" | "approved" | "sent" | "auto_sent" | "closed" | "hidden";
        /** Company */
        Company: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Email */
            email: string;
            /** Position */
            position: string | null;
            status: components["schemas"]["CompanyStatus"];
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string | null;
            /** Sent At */
            sent_at: string | null;
        };
        /** CompanyAdd */
        CompanyAdd: {
            /**
             * Name
             * @default
             */
            name?: string;
            /** Email */
            email: string;
            /**
             * Position
             * @default
             */
            position?: string;
        };
        /**
         * CompanyStatus
         * @enum {string}
         */
        CompanyStatus: "new" | "queued" | "sent" | "error";
        /** CompanyStatusChange */
        CompanyStatusChange: {
            /** Ids */
            ids: number[];
            status: components["schemas"]["CompanyStatus"];
        };
        /** CompanyUpdate */
        CompanyUpdate: {
            /**
             * Name
             * @default
             */
            name?: string;
            /**
             * Position
             * @default
             */
            position?: string;
        };
        /** Contacts */
        Contacts: {
            /**
             * Emails
             * @default []
             */
            emails: string[];
            /**
             * Phones
             * @default []
             */
            phones: string[];
            /**
             * Telegram
             * @default []
             */
            telegram: string[];
            /**
             * Person
             * @default
             */
            person: string;
        };
        /** Count */
        Count: {
            /** Count */
            count: number;
        };
        /** DayCount */
        DayCount: {
            /** Day */
            day: string | null;
            /** Hh */
            hh: number;
            /** Mail */
            mail: number;
        };
        /** Draft */
        Draft: {
            /** Text */
            text: string;
        };
        /**
         * Experience
         * @enum {string}
         */
        Experience: "noExperience" | "between1And3" | "between3And6" | "moreThan6";
        /** FollowupCandidate */
        FollowupCandidate: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            /** Url */
            url: string;
            stage: components["schemas"]["Stage"] | null;
            /** Sent */
            sent: string | null;
        };
        /** FollowupClose */
        FollowupClose: {
            /** Action */
            action: string;
        };
        /** FollowupSend */
        FollowupSend: {
            /** Text */
            text: string;
        };
        /** FormAnswer */
        FormAnswer: {
            /** Q */
            q: string;
            /** A */
            a: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HhMode
         * @enum {string}
         */
        HhMode: "resume" | "query";
        /** HhResume */
        HhResume: {
            /** Hash */
            hash: string;
            /** Title */
            title: string;
        };
        /** Ids */
        Ids: {
            /** Ids */
            ids: number[];
        };
        /** LogLine */
        LogLine: {
            /** Ts */
            ts: string;
            /** Msg */
            msg: string;
        };
        /** MailPreview */
        MailPreview: {
            /** To */
            to: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Attachments */
            attachments: string[];
        };
        /** MailTest */
        MailTest: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /** Ok */
        Ok: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** Pipeline */
        Pipeline: {
            /** Stages */
            stages: components["schemas"]["StageInfo"][];
            /** Cards */
            cards: components["schemas"]["PipelineCard"][];
        };
        /** PipelineCard */
        PipelineCard: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Url */
            url: string;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            stage: components["schemas"]["Stage"] | null;
            /** Stage Manual */
            stage_manual: number | null;
            /** Stage At */
            stage_at: string | null;
            /** Notes */
            notes: string | null;
            /** Next Step */
            next_step: string | null;
            /** Next At */
            next_at: string | null;
            /** Hh State */
            hh_state: string | null;
            /** Applied At */
            applied_at: string | null;
            /** Created At */
            created_at: string | null;
            /** Followup */
            followup: string | null;
        };
        /**
         * PipelineUpdate
         * @description Only the fields you send are changed.
         */
        PipelineUpdate: {
            stage?: components["schemas"]["Stage"] | null;
            /** Notes */
            notes?: string | null;
            /** Next Step */
            next_step?: string | null;
            /** Next At */
            next_at?: string | null;
        };
        /** PlannedStep */
        PlannedStep: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            stage: components["schemas"]["Stage"] | null;
            /** Next Step */
            next_step: string | null;
            /** Next At */
            next_at: string;
        };
        /** Question */
        Question: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Source */
            source: string | null;
            /** Seen */
            seen: number;
            /** Created At */
            created_at: string | null;
        };
        /** QueueNew */
        QueueNew: {
            /**
             * Source
             * @default hh
             */
            source?: string;
        };
        /** Reason */
        Reason: {
            /** Ok */
            ok: boolean;
            /** Text */
            text: string;
        };
        /** Reminders */
        Reminders: {
            /** Upcoming */
            upcoming: components["schemas"]["PlannedStep"][];
            /** Past */
            past: components["schemas"]["PlannedStep"][];
            /** Followups */
            followups: components["schemas"]["FollowupCandidate"][];
        };
        /** ResumeCount */
        ResumeCount: {
            /** Resume */
            resume: string;
            /** N */
            n: number;
            /** Invites */
            invites: number | null;
            /** Discards */
            discards: number | null;
        };
        /** ResumeUploaded */
        ResumeUploaded: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Name */
            name: string;
        };
        /** SearchChat */
        SearchChat: {
            /** Id */
            id: number;
            /** Chat Id */
            chat_id: string | null;
            /** Company */
            company: string | null;
            /** Vacancy */
            vacancy: string | null;
            /** Message */
            message: string | null;
            status: components["schemas"]["ChatStatus"];
            /** Created At */
            created_at: string | null;
        };
        /** SearchCompany */
        SearchCompany: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Email */
            email: string;
            /** Position */
            position: string | null;
            status: components["schemas"]["CompanyStatus"];
        };
        /** SearchResult */
        SearchResult: {
            /** Vacancies */
            vacancies: components["schemas"]["SearchVacancy"][];
            /** Chats */
            chats: components["schemas"]["SearchChat"][];
            /** Companies */
            companies: components["schemas"]["SearchCompany"][];
        };
        /** SearchVacancy */
        SearchVacancy: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            status: components["schemas"]["VacancyStatus"];
            /** Created At */
            created_at: string | null;
        };
        /**
         * SettingsOut
         * @description What the page sees: the password itself never leaves the server.
         */
        SettingsOut: {
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /**
             * Phone
             * @default
             */
            phone: string;
            /**
             * Desired Position
             * @default
             */
            desired_position: string;
            /**
             * Resume File
             * @default
             */
            resume_file: string;
            /**
             * Hh Domain
             * @default hh.kz
             */
            hh_domain: string;
            /** @default resume */
            hh_mode: components["schemas"]["HhMode"];
            /**
             * Hh Resume Hash
             * @default
             */
            hh_resume_hash: string;
            /**
             * Hh Resumes
             * @default []
             */
            hh_resumes: components["schemas"]["HhResume"][];
            /**
             * Hh Query
             * @default
             */
            hh_query: string;
            /**
             * Hh Area
             * @default
             */
            hh_area: string;
            /**
             * Hh Pages
             * @default 3
             */
            hh_pages: number;
            /**
             * Hh Daily Limit
             * @default 50
             */
            hh_daily_limit: number;
            /**
             * Hh Weekly Goal
             * @default 150
             */
            hh_weekly_goal: number;
            /**
             * Hh Pause Min
             * @default 4
             */
            hh_pause_min: number;
            /**
             * Hh Pause Max
             * @default 9
             */
            hh_pause_max: number;
            /**
             * Hh Exclude
             * @default
             */
            hh_exclude: string;
            /**
             * Hh Letter Template
             * @default Здравствуйте!
             *
             *     Меня заинтересовала вакансия «{position}» в компании {company}. Буду рад(а) обсудить, чем могу быть полезен(на) вашей команде.
             *
             *     С уважением,
             *     {name}
             *     {phone}
             */
            hh_letter_template: string;
            /** F Salary Min */
            f_salary_min: number | null;
            /**
             * F Skip No Salary
             * @default false
             */
            f_skip_no_salary: boolean;
            /**
             * F Experience
             * @default []
             */
            f_experience: components["schemas"]["Experience"][];
            /**
             * F Exclude Companies
             * @default
             */
            f_exclude_companies: string;
            /**
             * F Skip Rejected
             * @default true
             */
            f_skip_rejected: boolean;
            /**
             * F Min Match
             * @default 0
             */
            f_min_match: number;
            /**
             * F Sort Match
             * @default true
             */
            f_sort_match: boolean;
            /**
             * Chat Auto
             * @default true
             */
            chat_auto: boolean;
            /**
             * Chat Max
             * @default 20
             */
            chat_max: number;
            /**
             * Chat Robot Steps
             * @default 10
             */
            chat_robot_steps: number;
            /**
             * Smtp Host
             * @default smtp.gmail.com
             */
            smtp_host: string;
            /**
             * Smtp Port
             * @default 465
             */
            smtp_port: number;
            /**
             * Smtp User
             * @default
             */
            smtp_user: string;
            /**
             * Mail Daily Limit
             * @default 80
             */
            mail_daily_limit: number;
            /**
             * Mail Delay Min
             * @default 40
             */
            mail_delay_min: number;
            /**
             * Mail Delay Max
             * @default 90
             */
            mail_delay_max: number;
            /**
             * Mail Subject Template
             * @default Резюме: {name} — {position}
             */
            mail_subject_template: string;
            /**
             * Mail Body Template
             * @default Здравствуйте!
             *
             *     Меня зовут {name}. Хотел(а) бы предложить свою кандидатуру на позицию «{position}» в {company}. Резюме во вложении.
             *
             *     Буду благодарен(на) за обратную связь.
             *
             *     С уважением,
             *     {name}
             *     {phone}
             */
            mail_body_template: string;
            /**
             * Autopilot On
             * @default false
             */
            autopilot_on: boolean;
            /** @default review */
            autopilot_mode: components["schemas"]["AutopilotMode"];
            /**
             * Autopilot Interval
             * @default 30
             */
            autopilot_interval: number;
            /**
             * Autopilot From
             * @default 8
             */
            autopilot_from: number;
            /**
             * Autopilot To
             * @default 22
             */
            autopilot_to: number;
            /**
             * Other Query
             * @default
             */
            other_query: string;
            /**
             * Other Sites
             * @default [
             *       "habr",
             *       "enbek"
             *     ]
             */
            other_sites: string[];
            /**
             * Other Pages
             * @default 2
             */
            other_pages: number;
            /**
             * Other Countries
             * @default
             */
            other_countries: string;
            /**
             * Other Monitor
             * @default true
             */
            other_monitor: boolean;
            /**
             * Other Max Details
             * @default 40
             */
            other_max_details: number;
            /**
             * Followup Days
             * @default 5
             */
            followup_days: number;
            /**
             * Followup Template
             * @default Здравствуйте! Несколько дней назад я откликнулся(ась) на вакансию «{position}». Подскажите, пожалуйста, актуальна ли она и удобно ли обсудить мою кандидатуру? Буду рад(а) ответить на любые вопросы.
             *
             *     С уважением,
             *     {name}
             */
            followup_template: string;
            /**
             * Has Password
             * @default false
             */
            has_password: boolean;
            /**
             * Resume Name
             * @default
             */
            resume_name: string;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Desired Position */
            desired_position?: string | null;
            /** Hh Domain */
            hh_domain?: string | null;
            hh_mode?: components["schemas"]["HhMode"] | null;
            /** Hh Resume Hash */
            hh_resume_hash?: string | null;
            /** Hh Query */
            hh_query?: string | null;
            /** Hh Area */
            hh_area?: string | null;
            /** Hh Pages */
            hh_pages?: number | null;
            /** Hh Daily Limit */
            hh_daily_limit?: number | null;
            /** Hh Weekly Goal */
            hh_weekly_goal?: number | null;
            /** Hh Pause Min */
            hh_pause_min?: number | null;
            /** Hh Pause Max */
            hh_pause_max?: number | null;
            /** Hh Exclude */
            hh_exclude?: string | null;
            /** Hh Letter Template */
            hh_letter_template?: string | null;
            /** F Salary Min */
            f_salary_min?: number | null;
            /** F Skip No Salary */
            f_skip_no_salary?: boolean | null;
            /** F Experience */
            f_experience?: components["schemas"]["Experience"][] | null;
            /** F Exclude Companies */
            f_exclude_companies?: string | null;
            /** F Skip Rejected */
            f_skip_rejected?: boolean | null;
            /** F Min Match */
            f_min_match?: number | null;
            /** F Sort Match */
            f_sort_match?: boolean | null;
            /** Chat Auto */
            chat_auto?: boolean | null;
            /** Chat Max */
            chat_max?: number | null;
            /** Chat Robot Steps */
            chat_robot_steps?: number | null;
            /** Smtp Host */
            smtp_host?: string | null;
            /** Smtp Port */
            smtp_port?: number | null;
            /** Smtp User */
            smtp_user?: string | null;
            /** Smtp Password */
            smtp_password?: string | null;
            /** Mail Daily Limit */
            mail_daily_limit?: number | null;
            /** Mail Delay Min */
            mail_delay_min?: number | null;
            /** Mail Delay Max */
            mail_delay_max?: number | null;
            /** Mail Subject Template */
            mail_subject_template?: string | null;
            /** Mail Body Template */
            mail_body_template?: string | null;
            /** Autopilot On */
            autopilot_on?: boolean | null;
            autopilot_mode?: components["schemas"]["AutopilotMode"] | null;
            /** Autopilot Interval */
            autopilot_interval?: number | null;
            /** Autopilot From */
            autopilot_from?: number | null;
            /** Autopilot To */
            autopilot_to?: number | null;
            /** Other Query */
            other_query?: string | null;
            /** Other Sites */
            other_sites?: string[] | null;
            /** Other Pages */
            other_pages?: number | null;
            /** Other Countries */
            other_countries?: string | null;
            /** Other Monitor */
            other_monitor?: boolean | null;
            /** Other Max Details */
            other_max_details?: number | null;
            /** Followup Days */
            followup_days?: number | null;
            /** Followup Template */
            followup_template?: string | null;
        };
        /** SkipReason */
        SkipReason: {
            /** Note */
            note: string | null;
            /** N */
            n: number;
        };
        /**
         * Stage
         * @description Pipeline after the response.
         * @enum {string}
         */
        Stage: "applied" | "viewed" | "invited" | "interview" | "offer" | "declined";
        /** StageInfo */
        StageInfo: {
            id: components["schemas"]["Stage"];
            /** Label */
            label: string;
        };
        /** Started */
        Started: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Started */
            started: boolean;
        };
        /** StateCount */
        StateCount: {
            /** State */
            state: string;
            /** N */
            n: number;
        };
        /** Stats */
        Stats: {
            /** By Day */
            by_day: components["schemas"]["DayCount"][];
            /** Hh States */
            hh_states: components["schemas"]["StateCount"][];
            /** By Resume */
            by_resume: components["schemas"]["ResumeCount"][];
            /** Skipped */
            skipped: components["schemas"]["SkipReason"][];
        };
        /** Status */
        Status: {
            /** Running */
            running: boolean;
            /** Job */
            job: string | null;
            /** Log */
            log: components["schemas"]["LogLine"][];
            /** Vacancies */
            vacancies: {
                [key: string]: number;
            };
            /** Companies */
            companies: {
                [key: string]: number;
            };
            /** Applied Today */
            applied_today: number;
            week: components["schemas"]["Week"];
            /** Review */
            review: number;
            /** Sent Today */
            sent_today: number;
            /** Chats Pending */
            chats_pending: number;
            /** Attention */
            attention: number;
            /** Reminders */
            reminders: number;
            /** No Letter */
            no_letter: number;
            /** Autopilot Next */
            autopilot_next: string | null;
        };
        /** StatusChange */
        StatusChange: {
            /** Ids */
            ids: number[];
            status: components["schemas"]["VacancyStatus"];
            /**
             * Review
             * @default false
             */
            review?: boolean;
        };
        /** TaskInfo */
        TaskInfo: {
            /** Key */
            key: string;
            /** Title */
            title: string;
        };
        /** ToCompaniesResult */
        ToCompaniesResult: {
            /** Added */
            added: number;
            /** No Email */
            no_email: number;
        };
        /** Vacancy */
        Vacancy: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Ext Id */
            ext_id: string | null;
            /** Url */
            url: string;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            status: components["schemas"]["VacancyStatus"];
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string | null;
            /** Applied At */
            applied_at: string | null;
            /** Resume */
            resume: string | null;
            /** Hh State */
            hh_state: string | null;
            /** Hh State At */
            hh_state_at: string | null;
            /** Letter Sent */
            letter_sent: number | null;
            /** Salary Text */
            salary_text: string | null;
            /** Salary From */
            salary_from: number | null;
            /** Salary To */
            salary_to: number | null;
            /** Experience */
            experience: string | null;
            /** Skill Match */
            skill_match: number | null;
            /** Invited At */
            invited_at: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            stage: components["schemas"]["Stage"] | null;
            /** Next Step */
            next_step: string | null;
            /** Next At */
            next_at: string | null;
            /** Followup */
            followup: string | null;
            /** Location */
            location: string | null;
            /** Country */
            country: string | null;
            /** Remote */
            remote: number | null;
            /** Summary */
            summary: string | null;
            /** Company Url */
            company_url: string | null;
            /** Skills */
            skills: string | null;
            contacts: components["schemas"]["Contacts"] | null;
        };
        /** VacancyAdd */
        VacancyAdd: {
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title?: string;
            /**
             * Company
             * @default
             */
            company?: string;
            /**
             * Source
             * @default other
             */
            source?: string;
        };
        /** VacancyDetail */
        VacancyDetail: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Ext Id */
            ext_id: string | null;
            /** Url */
            url: string;
            /** Title */
            title: string | null;
            /** Company */
            company: string | null;
            status: components["schemas"]["VacancyStatus"];
            /** Note */
            note: string | null;
            /** Created At */
            created_at: string | null;
            /** Applied At */
            applied_at: string | null;
            /** Resume */
            resume: string | null;
            /** Hh State */
            hh_state: string | null;
            /** Hh State At */
            hh_state_at: string | null;
            /** Letter Sent */
            letter_sent: number | null;
            /** Salary Text */
            salary_text: string | null;
            /** Salary From */
            salary_from: number | null;
            /** Salary To */
            salary_to: number | null;
            /** Experience */
            experience: string | null;
            /** Skill Match */
            skill_match: number | null;
            /** Invited At */
            invited_at: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            stage: components["schemas"]["Stage"] | null;
            /** Next Step */
            next_step: string | null;
            /** Next At */
            next_at: string | null;
            /** Followup */
            followup: string | null;
            /** Location */
            location: string | null;
            /** Country */
            country: string | null;
            /** Remote */
            remote: number | null;
            /** Summary */
            summary: string | null;
            /** Company Url */
            company_url: string | null;
            /** Skills */
            skills: string | null;
            contacts: components["schemas"]["Contacts"] | null;
            /** Letter */
            letter: string | null;
            /** Notes */
            notes: string | null;
            /** Stage Manual */
            stage_manual: number | null;
            /** Stage At */
            stage_at: string | null;
            /** Followup Text */
            followup_text: string | null;
            /**
             * Match Info
             * @default []
             */
            match_info: components["schemas"]["Reason"][];
            /**
             * Form Answers
             * @default []
             */
            form_answers: components["schemas"]["FormAnswer"][];
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["VacancyEvent"][];
            /**
             * Chats
             * @default []
             */
            chats: components["schemas"]["ChatItem"][];
        };
        /** VacancyEvent */
        VacancyEvent: {
            /** Ts */
            ts: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
        };
        /**
         * VacancySource
         * @enum {string}
         */
        VacancySource: "hh" | "habr" | "enbek" | "other";
        /**
         * VacancyStatus
         * @enum {string}
         */
        VacancyStatus: "new" | "queued" | "applied" | "skipped" | "attention" | "error";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Week */
        Week: {
            /** Start */
            start: string;
            /** Invites */
            invites: number;
            /** Applied */
            applied: number;
            /** Applied All */
            applied_all: number;
            /** Invites All */
            invites_all: number;
            /** Rate */
            rate: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeUploaded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vacancies: {
        parameters: {
            query?: {
                source?: components["schemas"]["VacancySource"] | null;
                status?: components["schemas"]["VacancyStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_vacancy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"][];
                };
            };
        };
    };
    change_vacancy_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_all_new: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueNew"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Count"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_vacancies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ids"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    to_companies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ids"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToCompaniesResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vacancy_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pipeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    followup_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_followup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowupSend"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Started"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_followup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowupClose"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pipeline"];
                };
            };
        };
    };
    get_reminders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminders"];
                };
            };
        };
    };
    list_companies: {
        parameters: {
            query?: {
                status?: components["schemas"]["CompanyStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_company: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_companies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_companies"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Added"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_company_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyStatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_companies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ids"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mail_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mail_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailTest"];
                };
            };
        };
    };
    list_chats: {
        parameters: {
            query?: {
                status?: components["schemas"]["ChatStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chats_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatItem"][];
                };
            };
        };
    };
    reply_chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatReply"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Started"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hide_chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_answers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer-Output"][];
                };
            };
        };
    };
    save_answers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersSave"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_answer: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerMatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"][];
                };
            };
        };
    };
    delete_question: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInfo"][];
                };
            };
        };
    };
    stop_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    start_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    global_search: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                what: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV for Excel (semicolons, UTF-8 BOM) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
